name: Hi

on:
  push:
    branches: [main]
    paths: [FancyAction/**]
  workflow_dispatch:
    inputs: 
      name:
        description: "who are you?"
        type: string
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  test-my-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
      - name: test-the-action
        id: action-checker
        uses: ./FancyAction
        with:
          who-to-greet: ${{ inputs.name }}
      - name: show output
        run: echo "the time was ${{ steps.action-checker.outputs.time }}"
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Test
    steps:
      - run: echo "🧪 Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Build
    environment: Load-Test
    steps:
      - run: |
          echo "🧪 Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    environment:
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - run: |
          echo "🚀 Step 1..."
          sleep 10
      - run: |
          echo "🚀 Step 2..."
          sleep 10
      - run: |
          echo "🚀 Step 3..."
          sleep 10
      - run: |
          echo "🚀 Step 4..."
          sleep 10
      - run: |
          echo "🚀 Step 5..."
          sleep 10
